### ISSUE TITLE
Specifying ghc-options

### ISSUE THREAD

**Issue by adamgundry** [iconnect/cabal2stack#6]
If my `cabal.project` file has
```
package somelocalpackage
    ghc-options: -Wall
```
it would be nice if the `stack.yaml` we generated could include
```
ghc-options:
    somelocalpackage: -Wall
```

However AFAICS the `ghc-options` are not part of the `plan.json` so this may not be trivial to achieve.

**Comment by adamgundry** [comment]
There are other options in `cabal.project` it would be useful to forward:
 * `allow-newer`
 * `with-compiler` -> `compiler`

But there are also options such as `resolver` and `system-ghc` which don't directly have a cabal equivalent. Currently we have command-line flags for these. Perhaps we should add the ability to specify an input YAML file of fields that get merged into the `stack.yaml` unmodified?

**Comment by adamgundry** [comment]
We chatted about this and came up with the following plan:
 * Add an `-i, --input` option comparable to `-o, --output` that takes a path to a YAML file
 * If specified, start with the input file, then overwrite any matching keys with the values calculated by `cabal2stack`
 * In particular, it is allowed for the input and output files to be the same

This allows two modes of operation:
 * Specify a minimal input YAML and have `cabal2stack` expand it
 * Specify the `stack.yaml` itself and have `cabalstack` mutate it by changing the dependencies etc.

**Comment by adinapoli** [comment]
This issue cropped up recently with `nike` -- Kieron was wondering why CI was taking ages to update to a newer version of Atlas, and indeed it boils down to the fact that nike builds using `stack`, but even if we added the `library-only` flag on the `cabal.project` file (which are not doing 🤦 ) this still won't translate back into the generated `stack.yaml`, unless we use do the "in-place" modification trick, but even that is not ideal for a number of reasons.
